# Multi-stage Dockerfile for dev and prod
FROM node:22-alpine AS base
WORKDIR /src
COPY package.json .
RUN npm install
COPY . .

# # Development image
# FROM base AS dev
# ENV NODE_ENV=development
# EXPOSE 3000
# CMD ["npm", "run", "dev"]

# Production image
FROM base AS prod
ENV NODE_ENV=production
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]