import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { Footer } from "@/components/layout/footer/Footer";
import Header from "@/components/header/Header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const agrandir = localFont({
  src: [
    {
      path: "./../public/fonts/pp-agrandir/Agrandir-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../public/fonts/pp-agrandir/Agrandir-TextBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./../public/fonts/pp-agrandir/Agrandir-GrandHeavy.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-agrandir",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${agrandir.variable}`}>
        <Header/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
